[book]
title = "Telegram Bot Indonesia"
description = "Panduan membuat bot Telegram"
authors = ["bangHasan"]
language = "en"

[output.html]
smart-punctuation = true
mathjax-support = false
site-url = "/"
git-repository-url = "https://github.com/banghasan/ebook-bot-telegram"
edit-url-template = "https://github.com/banghasan/ebook-bot-telegram/tree/main/{path}"
hash-files = true
#additional-css = ["asset/giscus.css", "asset/whichlang.css"]
#additional-js = ["asset/giscus.js", "asset/whichlang.js"]
additional-css = ["asset/giscus.css"]
additional-js = ["asset/giscus.js"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

#[preprocessor.pagetoc]
#scroll_offset = 10  # pixels added to scroll position for active header detection (default: 10)
