[book]
title = "Telegram Bot Indonesia"
description = "Panduan membuat bot Telegram"
authors = ["bangHasan"]
language = "en"

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/banghasan/ebook-bot-telegram"
edit-url-template = "https://github.com/banghasan/ebook-bot-telegram/tree/main/{path}"
hash-files = true
